/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as RotaRouteImport } from './routes/rota'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as PassagensRouteImport } from './routes/passagens'
import { Route as ImpactoRouteImport } from './routes/impacto'
import { Route as AjudaRouteImport } from './routes/ajuda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsuariosIndexRouteImport } from './routes/usuarios/index'
import { Route as PerfilIndexRouteImport } from './routes/perfil/index'
import { Route as OrganizacoesIndexRouteImport } from './routes/organizacoes/index'
import { Route as MotoristasIndexRouteImport } from './routes/motoristas/index'
import { Route as FrotasIndexRouteImport } from './routes/frotas/index'
import { Route as FrotaIndexRouteImport } from './routes/frota/index'
import { Route as ConfiguracoesIndexRouteImport } from './routes/configuracoes/index'
import { Route as PerfilVeiculoRouteImport } from './routes/perfil/veiculo'
import { Route as PerfilNotificacoesRouteImport } from './routes/perfil/notificacoes'
import { Route as OrganizacoesIdRouteImport } from './routes/organizacoes/$id'
import { Route as MotoristasIdRouteImport } from './routes/motoristas/$id'
import { Route as FrotasFleetIdRouteImport } from './routes/frotas/$fleetId'
import { Route as FrotaNovoRouteImport } from './routes/frota/novo'
import { Route as FrotaIdRouteImport } from './routes/frota/$id'
import { Route as UsuariosEditarIdRouteImport } from './routes/usuarios/editar.$id'
import { Route as MotoristasEditarIdRouteImport } from './routes/motoristas/editar.$id'
import { Route as FrotaEditarIdRouteImport } from './routes/frota/editar.$id'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const RotaRoute = RotaRouteImport.update({
  id: '/rota',
  path: '/rota',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const PassagensRoute = PassagensRouteImport.update({
  id: '/passagens',
  path: '/passagens',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactoRoute = ImpactoRouteImport.update({
  id: '/impacto',
  path: '/impacto',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaRoute = AjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosIndexRoute = UsuariosIndexRouteImport.update({
  id: '/usuarios/',
  path: '/usuarios/',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilIndexRoute = PerfilIndexRouteImport.update({
  id: '/perfil/',
  path: '/perfil/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizacoesIndexRoute = OrganizacoesIndexRouteImport.update({
  id: '/organizacoes/',
  path: '/organizacoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const MotoristasIndexRoute = MotoristasIndexRouteImport.update({
  id: '/motoristas/',
  path: '/motoristas/',
  getParentRoute: () => rootRouteImport,
} as any)
const FrotasIndexRoute = FrotasIndexRouteImport.update({
  id: '/frotas/',
  path: '/frotas/',
  getParentRoute: () => rootRouteImport,
} as any)
const FrotaIndexRoute = FrotaIndexRouteImport.update({
  id: '/frota/',
  path: '/frota/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesIndexRoute = ConfiguracoesIndexRouteImport.update({
  id: '/configuracoes/',
  path: '/configuracoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilVeiculoRoute = PerfilVeiculoRouteImport.update({
  id: '/perfil/veiculo',
  path: '/perfil/veiculo',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilNotificacoesRoute = PerfilNotificacoesRouteImport.update({
  id: '/perfil/notificacoes',
  path: '/perfil/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizacoesIdRoute = OrganizacoesIdRouteImport.update({
  id: '/organizacoes/$id',
  path: '/organizacoes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MotoristasIdRoute = MotoristasIdRouteImport.update({
  id: '/motoristas/$id',
  path: '/motoristas/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FrotasFleetIdRoute = FrotasFleetIdRouteImport.update({
  id: '/frotas/$fleetId',
  path: '/frotas/$fleetId',
  getParentRoute: () => rootRouteImport,
} as any)
const FrotaNovoRoute = FrotaNovoRouteImport.update({
  id: '/frota/novo',
  path: '/frota/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const FrotaIdRoute = FrotaIdRouteImport.update({
  id: '/frota/$id',
  path: '/frota/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosEditarIdRoute = UsuariosEditarIdRouteImport.update({
  id: '/usuarios/editar/$id',
  path: '/usuarios/editar/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MotoristasEditarIdRoute = MotoristasEditarIdRouteImport.update({
  id: '/motoristas/editar/$id',
  path: '/motoristas/editar/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FrotaEditarIdRoute = FrotaEditarIdRouteImport.update({
  id: '/frota/editar/$id',
  path: '/frota/editar/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/impacto': typeof ImpactoRoute
  '/passagens': typeof PassagensRoute
  '/relatorios': typeof RelatoriosRoute
  '/rota': typeof RotaRoute
  '/users': typeof UsersRoute
  '/frota/$id': typeof FrotaIdRoute
  '/frota/novo': typeof FrotaNovoRoute
  '/frotas/$fleetId': typeof FrotasFleetIdRoute
  '/motoristas/$id': typeof MotoristasIdRoute
  '/organizacoes/$id': typeof OrganizacoesIdRoute
  '/perfil/notificacoes': typeof PerfilNotificacoesRoute
  '/perfil/veiculo': typeof PerfilVeiculoRoute
  '/configuracoes/': typeof ConfiguracoesIndexRoute
  '/frota/': typeof FrotaIndexRoute
  '/frotas/': typeof FrotasIndexRoute
  '/motoristas/': typeof MotoristasIndexRoute
  '/organizacoes/': typeof OrganizacoesIndexRoute
  '/perfil/': typeof PerfilIndexRoute
  '/usuarios/': typeof UsuariosIndexRoute
  '/frota/editar/$id': typeof FrotaEditarIdRoute
  '/motoristas/editar/$id': typeof MotoristasEditarIdRoute
  '/usuarios/editar/$id': typeof UsuariosEditarIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/impacto': typeof ImpactoRoute
  '/passagens': typeof PassagensRoute
  '/relatorios': typeof RelatoriosRoute
  '/rota': typeof RotaRoute
  '/users': typeof UsersRoute
  '/frota/$id': typeof FrotaIdRoute
  '/frota/novo': typeof FrotaNovoRoute
  '/frotas/$fleetId': typeof FrotasFleetIdRoute
  '/motoristas/$id': typeof MotoristasIdRoute
  '/organizacoes/$id': typeof OrganizacoesIdRoute
  '/perfil/notificacoes': typeof PerfilNotificacoesRoute
  '/perfil/veiculo': typeof PerfilVeiculoRoute
  '/configuracoes': typeof ConfiguracoesIndexRoute
  '/frota': typeof FrotaIndexRoute
  '/frotas': typeof FrotasIndexRoute
  '/motoristas': typeof MotoristasIndexRoute
  '/organizacoes': typeof OrganizacoesIndexRoute
  '/perfil': typeof PerfilIndexRoute
  '/usuarios': typeof UsuariosIndexRoute
  '/frota/editar/$id': typeof FrotaEditarIdRoute
  '/motoristas/editar/$id': typeof MotoristasEditarIdRoute
  '/usuarios/editar/$id': typeof UsuariosEditarIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/impacto': typeof ImpactoRoute
  '/passagens': typeof PassagensRoute
  '/relatorios': typeof RelatoriosRoute
  '/rota': typeof RotaRoute
  '/users': typeof UsersRoute
  '/frota/$id': typeof FrotaIdRoute
  '/frota/novo': typeof FrotaNovoRoute
  '/frotas/$fleetId': typeof FrotasFleetIdRoute
  '/motoristas/$id': typeof MotoristasIdRoute
  '/organizacoes/$id': typeof OrganizacoesIdRoute
  '/perfil/notificacoes': typeof PerfilNotificacoesRoute
  '/perfil/veiculo': typeof PerfilVeiculoRoute
  '/configuracoes/': typeof ConfiguracoesIndexRoute
  '/frota/': typeof FrotaIndexRoute
  '/frotas/': typeof FrotasIndexRoute
  '/motoristas/': typeof MotoristasIndexRoute
  '/organizacoes/': typeof OrganizacoesIndexRoute
  '/perfil/': typeof PerfilIndexRoute
  '/usuarios/': typeof UsuariosIndexRoute
  '/frota/editar/$id': typeof FrotaEditarIdRoute
  '/motoristas/editar/$id': typeof MotoristasEditarIdRoute
  '/usuarios/editar/$id': typeof UsuariosEditarIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajuda'
    | '/impacto'
    | '/passagens'
    | '/relatorios'
    | '/rota'
    | '/users'
    | '/frota/$id'
    | '/frota/novo'
    | '/frotas/$fleetId'
    | '/motoristas/$id'
    | '/organizacoes/$id'
    | '/perfil/notificacoes'
    | '/perfil/veiculo'
    | '/configuracoes/'
    | '/frota/'
    | '/frotas/'
    | '/motoristas/'
    | '/organizacoes/'
    | '/perfil/'
    | '/usuarios/'
    | '/frota/editar/$id'
    | '/motoristas/editar/$id'
    | '/usuarios/editar/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajuda'
    | '/impacto'
    | '/passagens'
    | '/relatorios'
    | '/rota'
    | '/users'
    | '/frota/$id'
    | '/frota/novo'
    | '/frotas/$fleetId'
    | '/motoristas/$id'
    | '/organizacoes/$id'
    | '/perfil/notificacoes'
    | '/perfil/veiculo'
    | '/configuracoes'
    | '/frota'
    | '/frotas'
    | '/motoristas'
    | '/organizacoes'
    | '/perfil'
    | '/usuarios'
    | '/frota/editar/$id'
    | '/motoristas/editar/$id'
    | '/usuarios/editar/$id'
  id:
    | '__root__'
    | '/'
    | '/ajuda'
    | '/impacto'
    | '/passagens'
    | '/relatorios'
    | '/rota'
    | '/users'
    | '/frota/$id'
    | '/frota/novo'
    | '/frotas/$fleetId'
    | '/motoristas/$id'
    | '/organizacoes/$id'
    | '/perfil/notificacoes'
    | '/perfil/veiculo'
    | '/configuracoes/'
    | '/frota/'
    | '/frotas/'
    | '/motoristas/'
    | '/organizacoes/'
    | '/perfil/'
    | '/usuarios/'
    | '/frota/editar/$id'
    | '/motoristas/editar/$id'
    | '/usuarios/editar/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjudaRoute: typeof AjudaRoute
  ImpactoRoute: typeof ImpactoRoute
  PassagensRoute: typeof PassagensRoute
  RelatoriosRoute: typeof RelatoriosRoute
  RotaRoute: typeof RotaRoute
  UsersRoute: typeof UsersRoute
  FrotaIdRoute: typeof FrotaIdRoute
  FrotaNovoRoute: typeof FrotaNovoRoute
  FrotasFleetIdRoute: typeof FrotasFleetIdRoute
  MotoristasIdRoute: typeof MotoristasIdRoute
  OrganizacoesIdRoute: typeof OrganizacoesIdRoute
  PerfilNotificacoesRoute: typeof PerfilNotificacoesRoute
  PerfilVeiculoRoute: typeof PerfilVeiculoRoute
  ConfiguracoesIndexRoute: typeof ConfiguracoesIndexRoute
  FrotaIndexRoute: typeof FrotaIndexRoute
  FrotasIndexRoute: typeof FrotasIndexRoute
  MotoristasIndexRoute: typeof MotoristasIndexRoute
  OrganizacoesIndexRoute: typeof OrganizacoesIndexRoute
  PerfilIndexRoute: typeof PerfilIndexRoute
  UsuariosIndexRoute: typeof UsuariosIndexRoute
  FrotaEditarIdRoute: typeof FrotaEditarIdRoute
  MotoristasEditarIdRoute: typeof MotoristasEditarIdRoute
  UsuariosEditarIdRoute: typeof UsuariosEditarIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rota': {
      id: '/rota'
      path: '/rota'
      fullPath: '/rota'
      preLoaderRoute: typeof RotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passagens': {
      id: '/passagens'
      path: '/passagens'
      fullPath: '/passagens'
      preLoaderRoute: typeof PassagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impacto': {
      id: '/impacto'
      path: '/impacto'
      fullPath: '/impacto'
      preLoaderRoute: typeof ImpactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda': {
      id: '/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios/': {
      id: '/usuarios/'
      path: '/usuarios'
      fullPath: '/usuarios/'
      preLoaderRoute: typeof UsuariosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/': {
      id: '/perfil/'
      path: '/perfil'
      fullPath: '/perfil/'
      preLoaderRoute: typeof PerfilIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizacoes/': {
      id: '/organizacoes/'
      path: '/organizacoes'
      fullPath: '/organizacoes/'
      preLoaderRoute: typeof OrganizacoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motoristas/': {
      id: '/motoristas/'
      path: '/motoristas'
      fullPath: '/motoristas/'
      preLoaderRoute: typeof MotoristasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frotas/': {
      id: '/frotas/'
      path: '/frotas'
      fullPath: '/frotas/'
      preLoaderRoute: typeof FrotasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frota/': {
      id: '/frota/'
      path: '/frota'
      fullPath: '/frota/'
      preLoaderRoute: typeof FrotaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/': {
      id: '/configuracoes/'
      path: '/configuracoes'
      fullPath: '/configuracoes/'
      preLoaderRoute: typeof ConfiguracoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/veiculo': {
      id: '/perfil/veiculo'
      path: '/perfil/veiculo'
      fullPath: '/perfil/veiculo'
      preLoaderRoute: typeof PerfilVeiculoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/notificacoes': {
      id: '/perfil/notificacoes'
      path: '/perfil/notificacoes'
      fullPath: '/perfil/notificacoes'
      preLoaderRoute: typeof PerfilNotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizacoes/$id': {
      id: '/organizacoes/$id'
      path: '/organizacoes/$id'
      fullPath: '/organizacoes/$id'
      preLoaderRoute: typeof OrganizacoesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motoristas/$id': {
      id: '/motoristas/$id'
      path: '/motoristas/$id'
      fullPath: '/motoristas/$id'
      preLoaderRoute: typeof MotoristasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frotas/$fleetId': {
      id: '/frotas/$fleetId'
      path: '/frotas/$fleetId'
      fullPath: '/frotas/$fleetId'
      preLoaderRoute: typeof FrotasFleetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frota/novo': {
      id: '/frota/novo'
      path: '/frota/novo'
      fullPath: '/frota/novo'
      preLoaderRoute: typeof FrotaNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frota/$id': {
      id: '/frota/$id'
      path: '/frota/$id'
      fullPath: '/frota/$id'
      preLoaderRoute: typeof FrotaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios/editar/$id': {
      id: '/usuarios/editar/$id'
      path: '/usuarios/editar/$id'
      fullPath: '/usuarios/editar/$id'
      preLoaderRoute: typeof UsuariosEditarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motoristas/editar/$id': {
      id: '/motoristas/editar/$id'
      path: '/motoristas/editar/$id'
      fullPath: '/motoristas/editar/$id'
      preLoaderRoute: typeof MotoristasEditarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frota/editar/$id': {
      id: '/frota/editar/$id'
      path: '/frota/editar/$id'
      fullPath: '/frota/editar/$id'
      preLoaderRoute: typeof FrotaEditarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjudaRoute: AjudaRoute,
  ImpactoRoute: ImpactoRoute,
  PassagensRoute: PassagensRoute,
  RelatoriosRoute: RelatoriosRoute,
  RotaRoute: RotaRoute,
  UsersRoute: UsersRoute,
  FrotaIdRoute: FrotaIdRoute,
  FrotaNovoRoute: FrotaNovoRoute,
  FrotasFleetIdRoute: FrotasFleetIdRoute,
  MotoristasIdRoute: MotoristasIdRoute,
  OrganizacoesIdRoute: OrganizacoesIdRoute,
  PerfilNotificacoesRoute: PerfilNotificacoesRoute,
  PerfilVeiculoRoute: PerfilVeiculoRoute,
  ConfiguracoesIndexRoute: ConfiguracoesIndexRoute,
  FrotaIndexRoute: FrotaIndexRoute,
  FrotasIndexRoute: FrotasIndexRoute,
  MotoristasIndexRoute: MotoristasIndexRoute,
  OrganizacoesIndexRoute: OrganizacoesIndexRoute,
  PerfilIndexRoute: PerfilIndexRoute,
  UsuariosIndexRoute: UsuariosIndexRoute,
  FrotaEditarIdRoute: FrotaEditarIdRoute,
  MotoristasEditarIdRoute: MotoristasEditarIdRoute,
  UsuariosEditarIdRoute: UsuariosEditarIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
