/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as PassagensRouteImport } from './routes/passagens'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FrotaIndexRouteImport } from './routes/frota/index'
import { Route as FrotaAdicionarRouteImport } from './routes/frota/adicionar'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const PassagensRoute = PassagensRouteImport.update({
  id: '/passagens',
  path: '/passagens',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FrotaIndexRoute = FrotaIndexRouteImport.update({
  id: '/frota/',
  path: '/frota/',
  getParentRoute: () => rootRouteImport,
} as any)
const FrotaAdicionarRoute = FrotaAdicionarRouteImport.update({
  id: '/frota/adicionar',
  path: '/frota/adicionar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/impact': typeof ImpactRoute
  '/passagens': typeof PassagensRoute
  '/users': typeof UsersRoute
  '/frota/adicionar': typeof FrotaAdicionarRoute
  '/frota/': typeof FrotaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/impact': typeof ImpactRoute
  '/passagens': typeof PassagensRoute
  '/users': typeof UsersRoute
  '/frota/adicionar': typeof FrotaAdicionarRoute
  '/frota': typeof FrotaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/impact': typeof ImpactRoute
  '/passagens': typeof PassagensRoute
  '/users': typeof UsersRoute
  '/frota/adicionar': typeof FrotaAdicionarRoute
  '/frota/': typeof FrotaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/impact'
    | '/passagens'
    | '/users'
    | '/frota/adicionar'
    | '/frota/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/impact'
    | '/passagens'
    | '/users'
    | '/frota/adicionar'
    | '/frota'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/impact'
    | '/passagens'
    | '/users'
    | '/frota/adicionar'
    | '/frota/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ImpactRoute: typeof ImpactRoute
  PassagensRoute: typeof PassagensRoute
  UsersRoute: typeof UsersRoute
  FrotaAdicionarRoute: typeof FrotaAdicionarRoute
  FrotaIndexRoute: typeof FrotaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passagens': {
      id: '/passagens'
      path: '/passagens'
      fullPath: '/passagens'
      preLoaderRoute: typeof PassagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frota/': {
      id: '/frota/'
      path: '/frota'
      fullPath: '/frota/'
      preLoaderRoute: typeof FrotaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frota/adicionar': {
      id: '/frota/adicionar'
      path: '/frota/adicionar'
      fullPath: '/frota/adicionar'
      preLoaderRoute: typeof FrotaAdicionarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ImpactRoute: ImpactRoute,
  PassagensRoute: PassagensRoute,
  UsersRoute: UsersRoute,
  FrotaAdicionarRoute: FrotaAdicionarRoute,
  FrotaIndexRoute: FrotaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
