"""create weekly goals table

Revision ID: ad59d083773c
Revises: 002_drop_brake
Create Date: 2026-05-28 22:53:00.885285+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad59d083773c'
down_revision: Union[str, None] = '002_drop_brake'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organization')
    op.alter_column('fuel_prices_by_uf', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('uq_fuel_prices_by_uf_uf'), 'fuel_prices_by_uf', type_='unique')
    op.create_index(op.f('ix_fuel_prices_by_uf_uf'), 'fuel_prices_by_uf', ['uf'], unique=True)
    op.alter_column('technical_specs', 'emission_factor_diesel_s10',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('technical_specs', 'emission_factor_gasolina_c',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('technical_specs', 'emission_factor_etanol',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('technical_specs', 'idle_rate_leve',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('technical_specs', 'idle_rate_pesado',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('technical_specs', 'paper_co2_per_ticket',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('technical_specs', 'paper_water_per_ticket',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('technical_specs', 'ludic_tree_year_absorption',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('technical_specs', 'ludic_phone_charge_factor',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('technical_specs', 'ludic_coffee_factor',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('technical_specs', 'ludic_metaphor_units',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('technical_specs', 'baseline_pedagio_avg_wait_sec',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('technical_specs', 'baseline_estacionamento_avg_wait_sec',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('technical_specs', 'maint_cost_leve',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('technical_specs', 'maint_cost_pesado',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('technical_specs', 'accel_surge_leve',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('technical_specs', 'accel_surge_pesado',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('technical_specs', 'benchmark_kg_co2_per_km_car',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('technical_specs', 'benchmark_kg_co2_per_burger',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('technical_specs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('technical_specs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('technical_specs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('technical_specs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('technical_specs', 'benchmark_kg_co2_per_burger',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'2.5'::double precision"),
               existing_nullable=False)
    op.alter_column('technical_specs', 'benchmark_kg_co2_per_km_car',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0.12'::double precision"),
               existing_nullable=False)
    op.alter_column('technical_specs', 'accel_surge_pesado',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0.08'::double precision"),
               existing_nullable=False)
    op.alter_column('technical_specs', 'accel_surge_leve',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0.015'::double precision"),
               existing_nullable=False)
    op.alter_column('technical_specs', 'maint_cost_pesado',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0.25'::double precision"),
               existing_nullable=False)
    op.alter_column('technical_specs', 'maint_cost_leve',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0.05'::double precision"),
               existing_nullable=False)
    op.alter_column('technical_specs', 'baseline_estacionamento_avg_wait_sec',
               existing_type=sa.INTEGER(),
               server_default=sa.text('180'),
               existing_nullable=False)
    op.alter_column('technical_specs', 'baseline_pedagio_avg_wait_sec',
               existing_type=sa.INTEGER(),
               server_default=sa.text('300'),
               existing_nullable=False)
    op.alter_column('technical_specs', 'ludic_metaphor_units',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text('\'{"paper": {"ream_a4": 500.0, "notebook": 50.0, "toilet_roll": 150.0}, "water": {"flush": 6.0, "shower_8min": 60.0, "drinking_day": 2.0}, "carbon": {"burger": 2.5, "km_car": 0.12, "tree_year": 15.0}}\'::jsonb'),
               existing_nullable=False)
    op.alter_column('technical_specs', 'ludic_coffee_factor',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'10'::double precision"),
               existing_nullable=False)
    op.alter_column('technical_specs', 'ludic_phone_charge_factor',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'120'::double precision"),
               existing_nullable=False)
    op.alter_column('technical_specs', 'ludic_tree_year_absorption',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'15'::double precision"),
               existing_nullable=False)
    op.alter_column('technical_specs', 'paper_water_per_ticket',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0.5'::double precision"),
               existing_nullable=False)
    op.alter_column('technical_specs', 'paper_co2_per_ticket',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0.012'::double precision"),
               existing_nullable=False)
    op.alter_column('technical_specs', 'idle_rate_pesado',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0.00069'::double precision"),
               existing_nullable=False)
    op.alter_column('technical_specs', 'idle_rate_leve',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0.00027'::double precision"),
               existing_nullable=False)
    op.alter_column('technical_specs', 'emission_factor_etanol',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'0.44'::double precision"),
               existing_nullable=False)
    op.alter_column('technical_specs', 'emission_factor_gasolina_c',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'2.15'::double precision"),
               existing_nullable=False)
    op.alter_column('technical_specs', 'emission_factor_diesel_s10',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'2.51'::double precision"),
               existing_nullable=False)
    op.drop_index(op.f('ix_fuel_prices_by_uf_uf'), table_name='fuel_prices_by_uf')
    op.create_unique_constraint(op.f('uq_fuel_prices_by_uf_uf'), 'fuel_prices_by_uf', ['uf'], postgresql_nulls_not_distinct=False)
    op.alter_column('fuel_prices_by_uf', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.create_table('organization',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cnpj', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('organization_pkey')),
    sa.UniqueConstraint('cnpj', name=op.f('organization_cnpj_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
