"""add role and organization_id to users

Revision ID: bc4a842ee613
Revises: ad59d083773c
Create Date: 2026-05-30 19:29:19.511337+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bc4a842ee613'
down_revision: Union[str, None] = 'ad59d083773c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Enum('motorista', 'gestor_frota', 'admin', name='userrole'), nullable=False))
    op.add_column('users', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'])
    op.add_column('vehicles', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.add_column('vehicles', sa.Column('assigned_driver_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'vehicles', 'users', ['assigned_driver_id'], ['id'])
    op.create_foreign_key(None, 'vehicles', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_column('vehicles', 'assigned_driver_id')
    op.drop_column('vehicles', 'organization_id')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'organization_id')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
