export const ROUTE_LABELS: Record<string, string> = {
  "/login": "Entrar",
  "/": "Início",
  "/dashboard": "Dashboard",
  "/frotas/": "Frotas",
  "/frota/": "Veículos",
  "/relatorios": "Relatórios",
  "/motoristas/": "Motoristas",
  "/passagens-auditoria": "Passagens",
  "/usuarios/": "Usuários",
  "/usuarios/editar": "Editar Usuário",
  "/configuracoes/": "Configurações Gerais",
  "/perfil/": "Meu Perfil",
  "/perfil/notificacoes": "Notificações",
  "/perfil/veiculo": "Informações do Veículo",
  "/ajuda": "Ajuda e Suporte",
  "/impacto": "Meu Impacto",
  "/rota": "Calcular Rota",
  "/passagens": "Minhas Passagens",
  "/users": "Usuários",
};
